version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/javascript-node:1-22-bookworm
    container_name: boilerplate_app
    shm_size: '8gb'
    volumes:
      - ../../:/workspaces:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    networks:
      - boilerplate_docker_network

  db:
    image: postgres:latest
    container_name: boilerplate_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - ./execute_deploy_scripts.sh:/docker-entrypoint-initdb.d/execute_deploy_scripts.sh
      - ../sql/:/docker-entrypoint-initdb.d/sql/
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    networks:
      - boilerplate_docker_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: boilerplate_pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db
    ports:
      - "5050:80"
    networks:
      - boilerplate_docker_network

  maildev:
    image: maildev/maildev:latest
    container_name: boilerplate_maildev
    ports:
      - "8085:1080"
      - "8025:1025"
    networks:
      - boilerplate_docker_network

networks:
  boilerplate_docker_network:

volumes:
  postgres-data:
  pgadmin-data:
